# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sms', models.ManyToManyField(blank=True, related_name='sms', to='sms_engine.SMS')),
            ],
        ),
    ]
