# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='sms',
            name='response',
            field=models.TextField(default=b'', verbose_name='Message'),
        ),
    ]
