# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(0, 'high'), (1, 'normal'), (2, 'low')], default=1, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
