# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_engine', '0002_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='end_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='start_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='backend_alias',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Backend alias'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='sms',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
